name: Build wheel on win32
on: [push]
env:
  CIBW_BUILD_VERBOSITY: 1
  CIBW_ARCHS: "auto32"
  # Run the package tests using `pytest`
  # CIBW_TEST_REQUIRES: pytest
  # CIBW_TEST_COMMAND: python setup.py test
jobs:
      
  build_wheels_for_win:
    name: Build wheels on Win32
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: install openssl (32 bit)
        shell: pwsh
        run: choco install openssl --limitoutput --x86

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # Disable explicitly python 3.10 and building PyPy wheels
          CIBW_SKIP: cp310-* pp*
          CIBW_PRERELEASE_PYTHONS: False

      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl
